<?php

$categories = [
    ['id' => 'groceries', 'name' => 'Groceries / Food', 'default' => 'Grocery purchase', 'info' => 'Daily food items, supermarket purchases, cooking ingredients.'],
    ['id' => 'transportation', 'name' => 'Transportation', 'default' => 'Transport fare', 'info' => 'General transportation costs including jeepney, taxi, bus, or ride-sharing.'],
    ['id' => 'utilities', 'name' => 'Utilities', 'default' => 'Utility bill', 'info' => 'Bills such as electricity, water, Wi-Fi, and other home utilities.'],
    ['id' => 'mobile_load', 'name' => 'Mobile Load', 'default' => 'Phone load', 'info' => 'Prepaid mobile load or data purchase.'],
    ['id' => 'fuel', 'name' => 'Fuel', 'default' => 'Gasoline refill', 'info' => 'Gasoline or diesel refuel for motorcycles and cars.'],
    ['id' => 'snacks', 'name' => 'Snacks / Coffee', 'default' => 'Snack purchase', 'info' => 'Snacks, drinks, milk tea, or coffee purchases.'],
    ['id' => 'dining_out', 'name' => 'Dining Out', 'default' => 'Meal outside', 'info' => 'Restaurant or fast-food meals.'],
    ['id' => 'household_supplies', 'name' => 'Household Supplies', 'default' => 'Home supplies', 'info' => 'Cleaning supplies, toiletries, and household essentials.'],
    ['id' => 'laundry', 'name' => 'Laundry', 'default' => 'Laundry expense', 'info' => 'Laundry shop payment or detergent expenses.'],
    ['id' => 'personal_care', 'name' => 'Personal Care', 'default' => 'Hygiene items', 'info' => 'Skincare, soap, shampoo, toothpaste, grooming needs.'],
    ['id' => 'entertainment', 'name' => 'Entertainment', 'default' => 'Entertainment expense', 'info' => 'Movies, games, streaming services, recreational activities.'],
    ['id' => 'others', 'name' => 'Others', 'default' => '', 'info' => 'Any expense that doesn’t fall into existing categories.'],
    ['id' => 'housing', 'name' => 'Housing (Rent/Mortgage)', 'default' => 'Rent payment', 'info' => 'Rent, mortgage, housing fees, or landlord payments.'],
    ['id' => 'healthcare', 'name' => 'Healthcare / Medicine', 'default' => 'Medical expense', 'info' => 'Medicines, check-ups, clinic fees, vitamins, and health essentials.'],
    ['id' => 'insurance', 'name' => 'Insurance', 'default' => 'Insurance payment', 'info' => 'Insurance premiums such as life, car, or health insurance.'],
    ['id' => 'maintenance', 'name' => 'Repairs & Maintenance', 'default' => 'Repair cost', 'info' => 'Home repairs, handyman services, or equipment maintenance.'],
    ['id' => 'appliances', 'name' => 'Appliances', 'default' => 'Appliance purchase', 'info' => 'Small or large household appliance purchases.'],
    ['id' => 'furniture', 'name' => 'Furniture', 'default' => 'Furniture purchase', 'info' => 'Chairs, tables, cabinets, and home furniture items.'],
    ['id' => 'clothing', 'name' => 'Clothing', 'default' => 'Clothes purchase', 'info' => 'Clothes, shoes, accessories, or wardrobe items.'],
    ['id' => 'childcare', 'name' => 'Childcare', 'default' => 'Childcare items', 'info' => 'Baby needs, diapers, milk, childcare services.'],
    ['id' => 'school_supplies', 'name' => 'School Supplies', 'default' => 'School supplies', 'info' => 'Notebooks, pens, paper, and school-related materials.'],
    ['id' => 'tuition', 'name' => 'Tuition', 'default' => 'Tuition fee', 'info' => 'School tuition payments or educational fees.'],
    ['id' => 'debt_payment', 'name' => 'Debt Payment', 'default' => 'Debt payment', 'info' => 'Loan payments, borrowed money repayment, installment payments.'],
    ['id' => 'savings', 'name' => 'Savings', 'default' => 'Savings deposit', 'info' => 'Money placed into savings, bank deposits, cash savings.'],
    ['id' => 'investments', 'name' => 'Investments', 'default' => 'Investment deposit', 'info' => 'Stocks, crypto, mutual funds, or other investments.'],
    ['id' => 'car_maintenance', 'name' => 'Car Maintenance', 'default' => 'Car maintenance', 'info' => 'Oil change, tune-up, car wash, or mechanical services.'],
    ['id' => 'parking_toll', 'name' => 'Parking / Toll Fees', 'default' => 'Toll or parking', 'info' => 'Parking payments, toll booths, expressway fees.'],
    ['id' => 'public_transport', 'name' => 'Public Transport', 'default' => 'Transport fee', 'info' => 'Bus, jeep, train, or public transport costs.'],
    ['id' => 'gifts', 'name' => 'Gifts', 'default' => 'Gift purchase', 'info' => 'Gifts for birthdays, holidays, or special occasions.'],
    ['id' => 'hobbies', 'name' => 'Hobbies', 'default' => 'Hobby expense', 'info' => 'Hobby-related purchases such as gaming, art, or crafts.'],
    ['id' => 'sports_gym', 'name' => 'Sports / Gym', 'default' => 'Gym payment', 'info' => 'Gym membership, sports equipment, fitness activities.'],
    ['id' => 'emergency', 'name' => 'Emergency Expenses', 'default' => 'Emergency spending', 'info' => 'Unexpected urgent expenses such as hospital or sudden repairs.'],
    ['id' => 'unexpected', 'name' => 'Unexpected Repairs', 'default' => 'Unexpected cost', 'info' => 'Unplanned repairs for home, appliances, or items.'],
    ['id' => 'pet_food', 'name' => 'Pet Food', 'default' => 'Pet food', 'info' => 'Dog/cat food, treats, and regular pet feeding expenses.'],
    ['id' => 'pet_vet', 'name' => 'Pet Vet Visits', 'default' => 'Vet bill', 'info' => 'Vet services, vaccines, or medical treatment.'],
    ['id' => 'pet_grooming', 'name' => 'Pet Grooming', 'default' => 'Pet grooming cost', 'info' => 'Pet grooming, baths, trimming, or cleaning services.'],
    ['id' => 'subscriptions', 'name' => 'Subscriptions / Memberships', 'default' => 'Subscription fee', 'info' => 'Netflix, Spotify, memberships, or recurring services.'],
    ['id' => 'travel', 'name' => 'Travel / Vacation', 'default' => 'Travel expense', 'info' => 'Flights, hotels, accommodations, tours, or trips.'],
    ['id' => 'charity', 'name' => 'Charity / Donations', 'default' => 'Donation', 'info' => 'Donations to charities, religious institutions, or social causes.'],
    ['id' => 'technology', 'name' => 'Technology / Gadgets', 'default' => 'Gadget purchase', 'info' => 'Phones, laptops, accessories, or electronic devices.'],
    ['id' => 'events', 'name' => 'Events / Parties', 'default' => 'Event expense', 'info' => 'Birthday parties, celebrations, weddings, or gatherings.'],
    ['id' => 'subscriptions_software', 'name' => 'Software / Apps', 'default' => 'Software subscription', 'info' => 'Paid apps, software licenses, or digital tools.'],
    ['id' => 'office_supplies', 'name' => 'Office Supplies', 'default' => 'Office purchase', 'info' => 'Stationery, printer ink, and office-related items.'],
    ['id' => 'medical_devices', 'name' => 'Medical Devices', 'default' => 'Device purchase', 'info' => 'Wheelchairs, blood pressure monitors, or other medical equipment.'],
    ['id' => 'cosmetics', 'name' => 'Cosmetics / Beauty', 'default' => 'Cosmetics purchase', 'info' => 'Makeup, skincare, perfume, or beauty items.'],
];

return [
    ['id' => 'groceries', 'name' => 'Groceries / Food', 'default' => 'Grocery purchase', 'info' => 'Daily food items, supermarket purchases, cooking ingredients.'],
    ['id' => 'transportation', 'name' => 'Transportation', 'default' => 'Transport fare', 'info' => 'General transportation costs including jeepney, taxi, bus, or ride-sharing.'],
    ['id' => 'utilities', 'name' => 'Utilities', 'default' => 'Utility bill', 'info' => 'Bills such as electricity, water, Wi-Fi, and other home utilities.'],
    ['id' => 'mobile_load', 'name' => 'Mobile Load', 'default' => 'Phone load', 'info' => 'Prepaid mobile load or data purchase.'],
    ['id' => 'fuel', 'name' => 'Fuel', 'default' => 'Gasoline refill', 'info' => 'Gasoline or diesel refuel for motorcycles and cars.'],
    ['id' => 'snacks', 'name' => 'Snacks / Coffee', 'default' => 'Snack purchase', 'info' => 'Snacks, drinks, milk tea, or coffee purchases.'],
    ['id' => 'dining_out', 'name' => 'Dining Out', 'default' => 'Meal outside', 'info' => 'Restaurant or fast-food meals.'],
    ['id' => 'household_supplies', 'name' => 'Household Supplies', 'default' => 'Home supplies', 'info' => 'Cleaning supplies, toiletries, and household essentials.'],
    ['id' => 'laundry', 'name' => 'Laundry', 'default' => 'Laundry expense', 'info' => 'Laundry shop payment or detergent expenses.'],
    ['id' => 'personal_care', 'name' => 'Personal Care', 'default' => 'Hygiene items', 'info' => 'Skincare, soap, shampoo, toothpaste, grooming needs.'],
    ['id' => 'entertainment', 'name' => 'Entertainment', 'default' => 'Entertainment expense', 'info' => 'Movies, games, streaming services, recreational activities.'],
    ['id' => 'others', 'name' => 'Others', 'default' => '', 'info' => 'Any expense that doesn’t fall into existing categories.'],
    ['id' => 'housing', 'name' => 'Housing (Rent/Mortgage)', 'default' => 'Rent payment', 'info' => 'Rent, mortgage, housing fees, or landlord payments.'],
    ['id' => 'healthcare', 'name' => 'Healthcare / Medicine', 'default' => 'Medical expense', 'info' => 'Medicines, check-ups, clinic fees, vitamins, and health essentials.'],
    ['id' => 'insurance', 'name' => 'Insurance', 'default' => 'Insurance payment', 'info' => 'Insurance premiums such as life, car, or health insurance.'],
    ['id' => 'maintenance', 'name' => 'Repairs & Maintenance', 'default' => 'Repair cost', 'info' => 'Home repairs, handyman services, or equipment maintenance.'],
    ['id' => 'appliances', 'name' => 'Appliances', 'default' => 'Appliance purchase', 'info' => 'Small or large household appliance purchases.'],
    ['id' => 'furniture', 'name' => 'Furniture', 'default' => 'Furniture purchase', 'info' => 'Chairs, tables, cabinets, and home furniture items.'],
    ['id' => 'clothing', 'name' => 'Clothing', 'default' => 'Clothes purchase', 'info' => 'Clothes, shoes, accessories, or wardrobe items.'],
    ['id' => 'childcare', 'name' => 'Childcare', 'default' => 'Childcare items', 'info' => 'Baby needs, diapers, milk, childcare services.'],
    ['id' => 'school_supplies', 'name' => 'School Supplies', 'default' => 'School supplies', 'info' => 'Notebooks, pens, paper, and school-related materials.'],
    ['id' => 'tuition', 'name' => 'Tuition', 'default' => 'Tuition fee', 'info' => 'School tuition payments or educational fees.'],
    ['id' => 'debt_payment', 'name' => 'Debt Payment', 'default' => 'Debt payment', 'info' => 'Loan payments, borrowed money repayment, installment payments.'],
    ['id' => 'savings', 'name' => 'Savings', 'default' => 'Savings deposit', 'info' => 'Money placed into savings, bank deposits, cash savings.'],
    ['id' => 'investments', 'name' => 'Investments', 'default' => 'Investment deposit', 'info' => 'Stocks, crypto, mutual funds, or other investments.'],
    ['id' => 'car_maintenance', 'name' => 'Car Maintenance', 'default' => 'Car maintenance', 'info' => 'Oil change, tune-up, car wash, or mechanical services.'],
    ['id' => 'parking_toll', 'name' => 'Parking / Toll Fees', 'default' => 'Toll or parking', 'info' => 'Parking payments, toll booths, expressway fees.'],
    ['id' => 'public_transport', 'name' => 'Public Transport', 'default' => 'Transport fee', 'info' => 'Bus, jeep, train, or public transport costs.'],
    ['id' => 'gifts', 'name' => 'Gifts', 'default' => 'Gift purchase', 'info' => 'Gifts for birthdays, holidays, or special occasions.'],
    ['id' => 'hobbies', 'name' => 'Hobbies', 'default' => 'Hobby expense', 'info' => 'Hobby-related purchases such as gaming, art, or crafts.'],
    ['id' => 'sports_gym', 'name' => 'Sports / Gym', 'default' => 'Gym payment', 'info' => 'Gym membership, sports equipment, fitness activities.'],
    ['id' => 'emergency', 'name' => 'Emergency Expenses', 'default' => 'Emergency spending', 'info' => 'Unexpected urgent expenses such as hospital or sudden repairs.'],
    ['id' => 'unexpected', 'name' => 'Unexpected Repairs', 'default' => 'Unexpected cost', 'info' => 'Unplanned repairs for home, appliances, or items.'],
    ['id' => 'pet_food', 'name' => 'Pet Food', 'default' => 'Pet food', 'info' => 'Dog/cat food, treats, and regular pet feeding expenses.'],
    ['id' => 'pet_vet', 'name' => 'Pet Vet Visits', 'default' => 'Vet bill', 'info' => 'Vet services, vaccines, or medical treatment.'],
    ['id' => 'pet_grooming', 'name' => 'Pet Grooming', 'default' => 'Pet grooming cost', 'info' => 'Pet grooming, baths, trimming, or cleaning services.'],
    ['id' => 'subscriptions', 'name' => 'Subscriptions / Memberships', 'default' => 'Subscription fee', 'info' => 'Netflix, Spotify, memberships, or recurring services.'],
    ['id' => 'travel', 'name' => 'Travel / Vacation', 'default' => 'Travel expense', 'info' => 'Flights, hotels, accommodations, tours, or trips.'],
    ['id' => 'charity', 'name' => 'Charity / Donations', 'default' => 'Donation', 'info' => 'Donations to charities, religious institutions, or social causes.'],
    ['id' => 'technology', 'name' => 'Technology / Gadgets', 'default' => 'Gadget purchase', 'info' => 'Phones, laptops, accessories, or electronic devices.'],
    ['id' => 'events', 'name' => 'Events / Parties', 'default' => 'Event expense', 'info' => 'Birthday parties, celebrations, weddings, or gatherings.'],
    ['id' => 'subscriptions_software', 'name' => 'Software / Apps', 'default' => 'Software subscription', 'info' => 'Paid apps, software licenses, or digital tools.'],
    ['id' => 'office_supplies', 'name' => 'Office Supplies', 'default' => 'Office purchase', 'info' => 'Stationery, printer ink, and office-related items.'],
    ['id' => 'medical_devices', 'name' => 'Medical Devices', 'default' => 'Device purchase', 'info' => 'Wheelchairs, blood pressure monitors, or other medical equipment.'],
    ['id' => 'cosmetics', 'name' => 'Cosmetics / Beauty', 'default' => 'Cosmetics purchase', 'info' => 'Makeup, skincare, perfume, or beauty items.'],
];
